// Code generated by stream_generate.py. DO NOT EDIT.
#pragma once

#include <common/i_data_stream.h>

#include <cstdint>
#include <string_view>

namespace cycore {
namespace du {
namespace common {

struct StreamTopicContract {
    std::string_view topic;
    uint32_t topic_id;
    uint64_t schema_hash;
    cy::common::DataType expected_data_type;
    bool raw_probe_supported;
};

inline std::string_view BaseTopic(std::string_view topic) {
    const auto slash_pos = topic.find_last_of('/');
    if (slash_pos == std::string_view::npos) {
        return topic;
    }
    return topic.substr(slash_pos + 1);
}

inline std::string_view DataTypeToString(cy::common::DataType data_type) {
    switch (data_type) {
    case cy::common::DataType::Int16:
        return "Int16";
    case cy::common::DataType::Int32:
        return "Int32";
    case cy::common::DataType::Float32:
        return "Float32";
    case cy::common::DataType::UInt8:
        return "UInt8";
    case cy::common::DataType::CS16:
        return "CS16";
    case cy::common::DataType::CF32:
        return "CF32";
    case cy::common::DataType::RawBytes:
        return "RawBytes";
    }
    return "Unknown";
}

inline const StreamTopicContract* FindTopicContract(std::string_view topic) {
    const std::string_view base_topic = BaseTopic(topic);

    static constexpr StreamTopicContract kContracts[] = {
        {"system.heartbeat", 1, 0x73e3c1bc1be056f1ULL, cy::common::DataType::RawBytes, false},
        {"iq_waveform", 2, 0x7f92cbb1a2aed44fULL, cy::common::DataType::CS16, true},
        {"fft_spectrum", 3, 0x583f45bb0d5d60dbULL, cy::common::DataType::Float32, true},
        {"stft_waterfall", 4, 0x61c49301e7a6be97ULL, cy::common::DataType::RawBytes, false},
        {"range_doppler", 5, 0x8e7c9287b8d052dbULL, cy::common::DataType::Float32, true},
        {"pulse_compresssion", 6, 0xc27d5de97675a6c5ULL, cy::common::DataType::CS16, true},
    };

    for (const auto& contract : kContracts) {
        if (contract.topic == base_topic) {
            return &contract;
        }
    }
    return nullptr;
}

inline uint32_t GetTopicId(std::string_view topic) {
    const auto* contract = FindTopicContract(topic);
    return contract ? contract->topic_id : 0;
}

inline uint64_t GetSchemaHash(std::string_view topic) {
    const auto* contract = FindTopicContract(topic);
    return contract ? contract->schema_hash : 0;
}

inline cy::common::DataType GetExpectedDataType(std::string_view topic) {
    const auto* contract = FindTopicContract(topic);
    return contract ? contract->expected_data_type : cy::common::DataType::RawBytes;
}

inline bool SupportsRawProbeTopic(std::string_view topic) {
    const auto* contract = FindTopicContract(topic);
    return contract && contract->raw_probe_supported;
}

} // namespace common
} // namespace du
} // namespace cycore
