name: qt5core-example

services:
  qt5core-example:
    container_name: qt5core-thread-example
    platform: linux/arm64
    init: true
    build:
      context: ../..
      dockerfile: docker/qt5core/Dockerfile
      args:
        BASE_IMAGE: registry.chengyistudio.com/cxx/ubuntu:24.04
    image: ${QT5CORE_IMAGE:-registry.chengyistudio.com/cxx/qt5core-thread-example:0.1.0}
