services:
  # 黑盒内部：负责将数据从模拟物理网段传输过来
  sidecar-alpha:
    image: registry.chengyistudio.com/cxx/sidecar:latest
    pull_policy: missing
    network_mode: host
    ipc: shareable
    environment:
      - SIDECAR_UCX_ROLE=listen
      - TELEMETRY_HOST=127.0.0.1
      - SIDECAR_UPSTREAM_SLOT_COUNT=${SLOT_COUNT:-64}
      - SIDECAR_UPSTREAM_MAX_PAYLOAD_BYTES=${MAX_PAYLOAD_BYTES:-262144}
      - SIDECAR_UPSTREAM_TYPE_ID=2
      - SIDECAR_UPSTREAM_TYPE_VERSION=1
      - SIDECAR_DOWNSTREAM_SLOT_COUNT=${SLOT_COUNT:-64}
      - SIDECAR_DOWNSTREAM_MAX_PAYLOAD_BYTES=${MAX_PAYLOAD_BYTES:-262144}
      - SIDECAR_DOWNSTREAM_TYPE_ID=1
      - SIDECAR_DOWNSTREAM_TYPE_VERSION=1

  # 黑盒内部：模拟物理雷达，持续产生 100Hz 测试波形
  radar-source:
    image: registry.chengyistudio.com/cxx/ring-signalsource:latest
    pull_policy: missing
    network_mode: host
    ipc: service:sidecar-alpha
    depends_on:
      - sidecar-alpha

  # 【面向您的唯一接口】：这是数据流的终点，即您的“数据井”
  sidecar-beta:
    container_name: sidecar-beta
    image: registry.chengyistudio.com/cxx/sidecar:latest
    pull_policy: missing
    network_mode: host
    ipc: shareable
    environment:
      - SIDECAR_UCX_ROLE=connect
      - SIDECAR_UCX_PEER_HOST=127.0.0.1
      - TELEMETRY_HOST=127.0.0.1
      - SIDECAR_UPSTREAM_SLOT_COUNT=${SLOT_COUNT:-64}
      - SIDECAR_UPSTREAM_MAX_PAYLOAD_BYTES=${MAX_PAYLOAD_BYTES:-262144}
      - SIDECAR_UPSTREAM_TYPE_ID=1
      - SIDECAR_UPSTREAM_TYPE_VERSION=1
      - SIDECAR_DOWNSTREAM_SLOT_COUNT=${SLOT_COUNT:-64}
      - SIDECAR_DOWNSTREAM_MAX_PAYLOAD_BYTES=${MAX_PAYLOAD_BYTES:-262144}
      - SIDECAR_DOWNSTREAM_TYPE_ID=2
      - SIDECAR_DOWNSTREAM_TYPE_VERSION=1
    depends_on:
      - sidecar-alpha


