ARG OPENEULER_BASE=registry.chengyistudio.com/cxx/sidecar@sha256:0a2a7d06ea0cec3c191bde6536f701cd7447cb2c1da4099500e43a7414e2bdc2

FROM ${OPENEULER_BASE}

RUN test "$(uname -m)" = "aarch64" \
    && dnf install -y \
      autoconf \
      automake \
      ca-certificates \
      cmake \
      gcc-toolset-10-gcc \
      gcc-toolset-10-gcc-c++ \
      libnl3-devel \
      libtool \
      make \
      ninja-build \
      numactl-devel \
      pkgconf-pkg-config \
      protobuf-compiler \
      protobuf-devel \
      rdma-core-35.0-5.oe2003sp4 \
      rdma-core-devel-35.0-5.oe2003sp4 \
    && dnf clean all

ENV TOOLSET_ROOT=/opt/openEuler/gcc-toolset-10/root/usr
ENV PATH=/opt/openEuler/gcc-toolset-10/root/usr/bin:${PATH}
