services:
  # 【面向您的唯一接口】：这是您的网关，所有您产生的数据都喂给它
  sidecar-alpha:
    container_name: sidecar-alpha
    image: registry.chengyistudio.com/cxx/ring-sidecar:0.1.0
    network_mode: host
    ipc: shareable
    environment:
      - SIDECAR_UCX_ROLE=listen
